version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_TINYMCE_API_KEY=${VITE_TINYMCE_API_KEY}
    volumes:
      - ./web:/app
      - /app/node_modules

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules

  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10